{# CREATE SCHEMA DEMO;
CREATE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
); #}


CREATE SCHEMA IF NOT EXISTS DEMO;
CREATE TABLE IF NOT EXISTS HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);